---

parser: '@typescript-eslint/parser'

globals:
  it: true
  expect: true
  describe: true
  test: true
  jest: true

plugins:
- '@typescript-eslint'

extends:
- eslint:recommended
- plugin:@typescript-eslint/recommended
